### ISSUE TITLE
Filter by document metadata in policy search API

### ISSUE THREAD

**Issue by marcusodavies** [climatepolicyradar/cpr-issues#87]
It should be possible to filter by the following document level metadata fields in the search api:

- policy_date
- responses_list
- hazards_list
- policy_description
- sector_list
- instrument_list
- keywords

- [x] load sector and instrument assignments (1st and 2nd level) at passage level into the DB 
- [x] endpoint: access both-levelled assignments through `/policies/search`
- [x] endpoint: to return schemas for sectors and instruments
- [ ] allow keyword filtering on all the above fields
- [ ] allow user to filter by lower and upper policy year range

**Comment by chrisaballard** [comment]
Following discussion with @eurolife, have agreed that the sector and instrument api should accept a list of top level instruments/sectors. Since the lower levels are being stored in the index, these will need to be remapped to the appropriate lower levels using the instrument and sector hierarchy. This will avoid further ui changes.
